# Generated by Django 6.0.2 on 2026-03-07 14:01

import django.core.validators
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="0123456789",
                        help_text="Le numéro doit contenir exactement 10 chiffres (0355555555)",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro doit contenir exactement 10 chiffres (0355555555)",
                                regex="^0\\d{9}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="contact@depanneur-pc.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Hajaina dépannage PC",
                        max_length=200,
                        verbose_name="Nom du site",
                    ),
                ),
                (
                    "tech_name",
                    models.CharField(
                        default="Hajaina dépannage PC",
                        max_length=200,
                        verbose_name="Nom du technicien",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Informaticien de confiance",
                        help_text="Ex: Votre dépanneur de confiance",
                        max_length=200,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "availability",
                    models.TextField(
                        default="Du lundi au vendredi, de 9h à 17h",
                        verbose_name="Disponibilité",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Ex: #007bff",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accueil",
                "verbose_name_plural": "Accueil",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nom du service"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.IntegerField(
                        blank=True,
                        help_text="Ex : 10000",
                        null=True,
                        verbose_name="Prix",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji ou classe CSS",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="A propos", max_length=200, verbose_name="Titre"
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="about_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page A propos",
                "verbose_name_plural": "Page A propos",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du produit"),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Garantie"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji ou classe CSS",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hardware_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel",
                "verbose_name_plural": "Matériels",
                "db_table": "hardware_products",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du produit"),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Version"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji ou classe CSS",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Logiciel",
                "verbose_name_plural": "Logiciels",
                "db_table": "software_products",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
    ]
